export enum DiscountTaskStatus {
  UNKNOWN = 'UNKNOWN',
  NEW = 'NEW',
  SEEN = 'SEEN',
  APPROVED = 'APPROVED',
  PARTLY_APPROVED = 'PARTLY_APPROVED',
  DECLINED = 'DECLINED',
  AUTO_DECLINED = 'AUTO_DECLINED',
  DECLINED_BY_USER = 'DECLINED_BY_USER',
  COUPON = 'COUPON',
  PURCHASED = 'PURCHASED',
} 